apiVersion: v1
kind: Pod
metadata:
  name: samba
  labels:
    name: samba
spec:
  containers:
    - name: webserver
      image: docker.pkg.github.com/sirishbandi/samba/samba:latest
      ports:
        - containerPort: 445
          hostPort: 445
        - containerPort: 139
          hostPort: 139
      volumeMounts:
        - mountPath: /usr/data/users
          name: users
        - mountPath: /mnt
          name: share
  volumes:
    - name: users
      secret:
         secretName: users
    - name: share
      hostPath:
        path: /HDD
        type: Directory
